name: Scrape Sales Report

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes (UTC)
  workflow_dispatch: # Allows manual run

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pdfplumber

      - name: Run scraper
        run: python southlaw_scraper.py

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add sales_report.json
          git commit -m "Update sales report" || echo "No changes to commit"
          git push
